# SPDX-License-Identifier: GPL-2.0
ARG BASE_IMAGE
FROM ubuntu:23.10

ARG RUN_CMD

RUN apt -y update -qq && apt -y upgrade && \
	DEBIAN_FRONTEND=noninteractive apt -y install \
	ca-certificates curl $RUN_CMD

ARG TEST="/test.sh"
COPY src/test/$RUN_CMD.sh ${TEST}
RUN chmod +x ${TEST}

ARG ARG ENTRY="/entrypoint.sh"
RUN echo "#!/bin/bash\n$RUN_CMD \$@" > ${ENTRY} && chmod +x ${ENTRY}
ENTRYPOINT [ "/entrypoint.sh" ]
