# SPDX-License-Identifier: GPL-2.0
ARG BASE
FROM $BASE as builder

LABEL org.opencontainers.image.description="Java environment for https://github.com/hihg-um/flare.git"

RUN DEBIAN_FRONTEND=noninteractive apt -y install git

WORKDIR /src
RUN git clone https://github.com/hihg-um/flare.git  && \
	javac -cp flare/src/ flare/src/admix/AdmixMain.java && \
	jar cfe flare.jar admix/AdmixMain -C flare/src/ ./ && \
	jar -i flare.jar

FROM $BASE
ARG RUN_CMD

COPY --from=builder --chmod=0444 /src/flare.jar ${CLASSPATH}/

COPY --chmod=0555 src/test/$RUN_CMD.sh /test.sh
COPY --chmod=0555 src/run/$RUN_CMD.sh /

ENTRYPOINT [ "/flare.sh" ]
